# Generated by Django 4.2.3 on 2023-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
