# Generated by Django 4.2.3 on 2023-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Games', 'Games')], max_length=255, null=True),
        ),
    ]
