# Generated by Django 4.2.3 on 2023-12-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Accessories', 'Accessories'), ('Games', 'Games'), ('Clothing', 'Clothing'), ('General', 'General')], max_length=255, null=True),
        ),
    ]
